openapi: 3.0.2
  info:
    title: Alphabetical Order
  version: 0.0.0
  paths:
    /foo:
      get:
        operationId: get-foo
        responses:
          '200':
            description: ''
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/foo'
          '404':
            description: ''
  components:
    schemas:
      foo:
        title: More incorrect casing
        type: object
        properties:
          id:
            type: integer
          bar:
            type: string